# gen-versions.ps1 - read versions from the root mcpp.toml and regenerate
# src/versions.generated.h (used by config.cppm for the About dialog).
#
# mcpp has no compile-time version injection, so the version constants live in
# mcpp.toml only and this script (run after bumping versions) emits them into a
# generated header. Run from the repo root:
#   powershell -File scripts/gen-versions.ps1
#
# NOTE: keep this file ASCII-only. Windows PowerShell 5.1 reads a .ps1 without
# a UTF-8 BOM as ANSI; non-ASCII bytes (e.g. a Chinese comment) can decode to a
# quote character that breaks parsing / writes (same warning as make-dist.ps1).
#
# Extraction uses whole-file regexes pinned to each assignment form (mcpp.toml
# mixes CRLF/LF line endings and can glue a line onto its comment, so no line
# anchors). The output path is normalized to avoid `\..\` surprises.
param(
    [string]$Manifest = "$PSScriptRoot\..\mcpp.toml",
    [string]$Out      = "$PSScriptRoot\..\src\versions.generated.h"
)
$ErrorActionPreference = 'Stop'

$Manifest = [System.IO.Path]::GetFullPath($Manifest)
$Out      = [System.IO.Path]::GetFullPath($Out)
$content  = Get-Content $Manifest -Raw

function GetVer([string]$name, [string]$pattern) {
    $m = [regex]::Match($content, $pattern, [System.Text.RegularExpressions.RegexOptions]::Multiline)
    if ($m.Success) { return $m.Groups[1].Value }
    throw "mcpp.toml: could not find $name"
}
$app  = GetVer '[package].version'      '(?m)^version\s*=\s*"([^"]+)"'
$eui  = GetVer 'dependencies eui-neo'   'eui-neo\s*=\s*\{\s*version\s*=\s*"([^"]+)"'
$ws   = GetVer 'dependencies websocket' 'websocket\s*=\s*"([^"]+)"'
$json = GetVer 'dependencies json'      'json\s*=\s*"([^"]+)"'

$lines = @(
    '// versions.generated.h - GENERATED by scripts/gen-versions.ps1 / gen-versions.sh'
    '// from the root mcpp.toml. Do not edit by hand; regenerate after bumping versions:'
    '//   powershell -File scripts/gen-versions.ps1   (or  bash scripts/gen-versions.sh)'
    '#pragma once'
    ''
    "#define TINY_APP_VERSION `"$app`""
    "#define TINY_EUI_VERSION `"$eui`""
    "#define TINY_WS_VERSION `"$ws`""
    "#define TINY_JSON_VERSION `"$json`""
)
$generated = ($lines -join "`n") + "`n"

$existing = if (Test-Path $Out) { Get-Content $Out -Raw } else { '' }
if ($existing -ne $generated) {
    # WriteAllText writes $generated byte-for-byte (LF line endings, UTF-8 no
    # BOM) so it matches what gen-versions.sh produces. Set-Content would add
    # CRLF on Windows and break cross-script idempotency.
    [System.IO.File]::WriteAllText($Out, $generated, [System.Text.UTF8Encoding]::new($false))
    Write-Host "regenerated $Out"
} else {
    Write-Host "$Out unchanged"
}
