#!/usr/bin/env bash
# gen-versions.sh - read versions from the root mcpp.toml and regenerate
# src/versions.generated.h (used by config.cppm for the About dialog).
#
# mcpp has no compile-time version injection, so the version constants live in
# mcpp.toml only and this script (run after bumping versions) emits them into a
# generated header. Run from the repo root:  bash scripts/gen-versions.sh
#
# Extraction uses grep + cut-on-quotes (no regex escaping): mcpp.toml mixes
# CRLF/LF line endings and even glues a line onto its comment, so we pin each
# value to its assignment text and take the 2nd double-quoted field.
set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MANIFEST="$DIR/mcpp.toml"
OUT="$DIR/src/versions.generated.h"

field() { cut -d'"' -f2; }
APP="$(grep '^version' "$MANIFEST" | head -n1 | field)"
EUI="$(grep 'eui-neo' "$MANIFEST" | grep -o 'version = "[^"]*"' | head -n1 | field)"
WS="$(grep 'websocket = ' "$MANIFEST" | head -n1 | field)"
JSON="$(grep 'json = ' "$MANIFEST" | head -n1 | field)"

if [[ -z "$APP" || -z "$EUI" || -z "$WS" || -z "$JSON" ]]; then
  echo "error: could not extract all versions from $MANIFEST" >&2
  echo "  app=$APP eui=$EUI ws=$WS json=$JSON" >&2
  exit 1
fi

content=$(printf '%s\n' \
  '// versions.generated.h - GENERATED by scripts/gen-versions.ps1 / gen-versions.sh' \
  '// from the root mcpp.toml. Do not edit by hand; regenerate after bumping versions:' \
  '//   powershell -File scripts/gen-versions.ps1   (or  bash scripts/gen-versions.sh)' \
  '#pragma once' \
  '' \
  "#define TINY_APP_VERSION \"$APP\"" \
  "#define TINY_EUI_VERSION \"$EUI\"" \
  "#define TINY_WS_VERSION \"$WS\"" \
  "#define TINY_JSON_VERSION \"$JSON\"")

if [[ "$(cat "$OUT" 2>/dev/null || true)" != "$content" ]]; then
  printf '%s\n' "$content" > "$OUT"
  echo "regenerated $OUT"
else
  echo "$OUT unchanged"
fi
