// versions.generated.h - GENERATED by scripts/gen-versions.ps1 / gen-versions.sh
// from the root mcpp.toml. Do not edit by hand; regenerate after bumping versions:
//   powershell -File scripts/gen-versions.ps1   (or  bash scripts/gen-versions.sh)
#pragma once

#define TINY_APP_VERSION "0.5.9"
#define TINY_EUI_VERSION "0.5.6"
#define TINY_WS_VERSION "12.0.1"
#define TINY_JSON_VERSION "3.12.0"
